### ISSUE TITLE
Open source firmware test for rpi b+

### ISSUE THREAD

**Issue by shuaichen007** [Olde-Skuul/doom3do#3]
Hi Skuul,

Have you tested the "rpi-opensource-firmware" on the rpi b+ yet?

I am also interested in it and trying this firmware on rpi b+.

~Sincerely
Shuai Chen
Yale university

**Comment by rawr51919** [comment]
Isn't this unrelated to the actual repo itself? This isn't even an issue at all. @burgerbecky, if you want, you can close this issue and do with what it entails as you will.

**Comment by burgerbecky** [comment]
No, I haven't tried the firmware. However, @coltongit is correct, this is for issues with DOOM3DO, not general questions. If you want to send me messages, just send me a message on twitter or send an email in the email address in the license. I'll close this issue, since it's not an issue.
